Move UI components to separate files and add previews
khaletska/chess pull request #14
Opened 2024-07-11 16:26 UTC by Shiaulis

# Desk View
<img width="841" alt="image" src="https://github.com/khaletska/chess/assets/13601748/c1ae1494-6a05-414d-9579-03871d7bdcc0">

# Board View
<img width="1018" alt="image" src="https://github.com/khaletska/chess/assets/13601748/afba0f7c-cbf0-4455-b3ee-7c32191c55f0">

# Piece View
<img width="1000" alt="image" src="https://github.com/khaletska/chess/assets/13601748/8e990338-dfff-47ea-b744-fd682d347f49">

2024-07-11 16:27 UTC, Shiaulis commented
This solves the ticket https://github.com/khaletska/chess/issues/5

2024-07-12 08:46 UTC, khaletska commented
![image](https://github.com/user-attachments/assets/55bdc6fb-fd3b-4045-b551-e62b535723d9)

2024-07-12 10:07 UTC, khaletska requested changes
Only one comment

2024-07-12 10:07 UTC, khaletska commented on chess.xcodeproj/project.pbxproj
> +		B157A0E32C40365600810FCC /* DeskView.swift in Sources */ = {isa = PBXBuildFile; fileRef = B157A0DC2C40365500810FCC /* DeskView.swift */; };
Does it make sense if we call it ChessGameView?

2024-07-12 10:14 UTC, khaletska approved these changes

2024-07-12 10:15 UTC, merged