Move pieces
khaletska/chess pull request #17
Opened 2024-07-13 05:11 UTC by khaletska

- Added possibility to move any piece to any empty square
- Replaced all the cell coordinates occurrences with Coordinate structure

2024-07-13 05:12 UTC, khaletska commented on chess/ChessGameViewModel.swift
> +    func handleTap(at cellAddress: Coordinate) {
function naming is up for discussion

2024-07-13 07:48 UTC, Shiaulis commented on chess/ChessGameViewModel.swift
> +    func handleTap(at cellAddress: Coordinate) {
cell Tapped?

2024-07-13 07:50 UTC, Shiaulis commented on chess/ChessGameViewModel.swift
> +    func getPiece(for cell: Coordinate) -> ChessPiece? {
let's unify naming for parameters that have `Coordinate` type. Here it is a `cell` but down below it is `address`. I assume word `cell` is recerved by the logic so coordinate(s) or address would make more sense

2024-07-13 07:51 UTC, Shiaulis requested changes
works good, let's just improve naming a bit

2024-07-14 10:06 UTC, Shiaulis approved these changes

2024-07-14 10:31 UTC, merged