Draw full screen board in portrait mode
khaletska/chess pull request #2
Opened 2024-07-08 13:29 UTC by khaletska

Board is drawn in black and white, takes full screen but is not redrawn in the portrait mode

2024-07-09 07:50 UTC, Shiaulis requested changes
cannot check it since project file is not opening for me 😥

2024-07-09 16:02 UTC, Shiaulis requested changes
left some comments. Great achievement on making this work 💪🏾

2024-07-09 16:02 UTC, Shiaulis commented on chess/ContentView.swift
> +    let columns = Array(repeating: GridItem(.flexible(), spacing: 0), count: 8)
can it be private?

2024-07-09 16:02 UTC, Shiaulis commented on chess/ContentView.swift
> +    func getBorderColorForSquare(row: Int, col: Int) -> Color {
can it be private?

2024-07-09 16:02 UTC, Shiaulis commented on chess/ContentView.swift
> +    func getColorForSquare(row: Int, col: Int) -> Color {
can it be private?

2024-07-09 16:02 UTC, Shiaulis commented on chess/ContentView.swift
> +        return (row + col).isMultiple(of: 2) ? .white : .black
```suggestion
        (row + col).isMultiple(of: 2) ? .white : .black
```

2024-07-09 16:02 UTC, Shiaulis commented on chess/ContentView.swift
> +    let imageSize: CGFloat
can it be private?

2024-07-09 16:02 UTC, Shiaulis commented on chess/ContentView.swift
> +    let piece: ChessPiece?
why piece is optional? Maybe this view represents spot, клітинку, not piece?

2024-07-09 16:02 UTC, Shiaulis commented on chess/ContentView.swift
> +    func getBorderColorForSquare(row: Int, col: Int) -> Color {
okay it seems that since we don't have a view controller her we need an intermediate object between view and model. It might be in separate PR but let's eventually make some view model that contains logic like this method

2024-07-09 17:45 UTC, khaletska commented on chess/ContentView.swift
> +    func getBorderColorForSquare(row: Int, col: Int) -> Color {
I have to confess that I don't understand this concept at all for now. Will ofc try to achieve it for the next PR

2024-07-09 17:48 UTC, khaletska commented on chess/ContentView.swift
> +    let piece: ChessPiece?
Moved unwrapping piece out of this struct, now it is a piece. If you have any further structural improvement, I'll be happy to hear about them 🙌

2024-07-09 17:51 UTC, khaletska commented on chess/ContentView.swift
> +    let imageSize: CGFloat
Interesting. While it can be private, it requires then an explicit init.. Should I always do it like this?

2024-07-10 06:53 UTC, Shiaulis commented on chess/ContentView.swift
> +    let imageSize: CGFloat
I prefer this way. At least it helped me to make a discipline to make everything private

2024-07-10 07:05 UTC, Shiaulis approved these changes

2024-07-10 07:06 UTC, merged